version: "3"

services:
    frontend:
        build:
            context: ./Frontend
            dockerfile: Dockerfile
        ports:
            - "4444:4444"
        restart: always

    backend:
        build:
            context: ./Backend
            dockerfile: Dockerfile
        ports:
            - "4545:4545"
            - "4646:4646"
        restart: always